# version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf_qa_backend
    depends_on:
      - chroma
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data/chroma:/app/data/chroma
      - ./data/storage:/app/data/storage

  chroma:
    container_name: chroma_db
    image: chromadb/chroma:latest
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: /chroma_data
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/chroma_data

networks:
  default:
    name: pdf-qa-backend_default

